# Generated by Django 2.2 on 2020-07-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_numbers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
